name: Build and Test

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

concurrency:
  group: "${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: Setup and Test
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
          # cache: pip
          # cache-dependency-path: setup.py

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install module
        run: pip install .[tests]

      - name: Test with pytest
        run: pytest

      - name: Report coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./cov.xml

  deploy-dev:
    name: Deploy to GCF
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    environment:
      name: dev
    permissions:
      id-token: write
      contents: read

    steps:
      - name: ‚¨áÔ∏è Set up code
        uses: actions/checkout@v3

      - name: üóùÔ∏è Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          create_credentials_file: true
          token_format: access_token
          workload_identity_provider: ${{ secrets.IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

      - name: üöÄ Deploy to Cloud Function
        id: deploy
        uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: erap-skid
          runtime: python38
          entry_point: main
          source_dir: src/erap
          service_account_email: cloud-function-sa@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com
          event_trigger_type: providers/cloud.pubsub/eventTypes/topic.publish
          event_trigger_resource: projects/${{ secrets.PROJECT_ID }}/topics/monday-morning-topic
          deploy_timeout: 600
          secret_volumes: |
            /secrets/app/secrets.json=${{secrets.PROJECT_ID}}/secrets/secrets
            /secrets/ftp/known_hosts=${{secrets.PROJECT_ID}}/secrets/known_hosts

      - name: üì• Create PubSub topic
        run: |
          if [ ! "$(gcloud pubsub topics list | grep monday-morning-topic)" ]; then
            gcloud pubsub topics create monday-morning-topic --quiet
          fi

      - name: üï∞Ô∏è Create Cloud Scheduler
        run: |
          if [ ! "$(gcloud scheduler jobs list --location=us-central1 | grep monday-morning)" ]; then
            gcloud scheduler jobs create pubsub monday-morning \
              --description="Trigger the erap-skid bot once a week on monday morning" \
              --schedule="0 9 * * 1" \
              --time-zone=America/Denver \
              --location=us-central1 \
              --topic=monday-morning-topic \
              --message-body='{"run": "now"}' \
              --quiet
          else
            gcloud scheduler jobs update pubsub monday-morning \
              --description="Trigger the erap-skid bot once a week on monday morning" \
              --schedule="0 9 * * 1" \
              --time-zone=America/Denver \
              --location=us-central1 \
              --topic=monday-morning-topic \
              --message-body='{"run": "now"}' \
              --quiet
          fi

  test-secret-1:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    environment:
      name: dev
    permissions:
      id-token: write
      contents: read

    steps:
      - name: ‚¨áÔ∏è Set up code
        uses: actions/checkout@v3

      - name: üóùÔ∏è Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          create_credentials_file: true
          token_format: access_token
          workload_identity_provider: ${{ secrets.IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

      - name: full project id with version
        uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: id-with-version
          runtime: python38
          entry_point: main
          source_dir: src/erap
          service_account_email: cloud-function-sa@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com
          event_trigger_type: providers/cloud.pubsub/eventTypes/topic.publish
          event_trigger_resource: projects/${{ secrets.PROJECT_ID }}/topics/erap-scheduler
          deploy_timeout: 600
          secret_volumes: |
            /secrets/app/secrets.json=projects/${{secrets.PROJECT_ID}}/secrets/secrets/versions/1
            /secrets/ftp/known_hosts=projects/${{secrets.PROJECT_ID}}/secrets/known_hosts/versions/1

  test-secret-2:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    environment:
      name: dev
    permissions:
      id-token: write
      contents: read

    steps:
      - name: ‚¨áÔ∏è Set up code
        uses: actions/checkout@v3

      - name: üóùÔ∏è Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          create_credentials_file: true
          token_format: access_token
          workload_identity_provider: ${{ secrets.IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

      - name: full project id with implied latest
        uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: id-with-implied-version
          runtime: python38
          entry_point: main
          source_dir: src/erap
          service_account_email: cloud-function-sa@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com
          event_trigger_type: providers/cloud.pubsub/eventTypes/topic.publish
          event_trigger_resource: projects/${{ secrets.PROJECT_ID }}/topics/erap-scheduler
          deploy_timeout: 600
          secret_volumes: |
            /secrets/app/secrets.json=projects/${{secrets.PROJECT_ID}}/secrets/secrets
            /secrets/ftp/known_hosts=projects/${{secrets.PROJECT_ID}}/secrets/known_hosts

  test-secret-3:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    environment:
      name: dev
    permissions:
      id-token: write
      contents: read

    steps:
      - name: ‚¨áÔ∏è Set up code
        uses: actions/checkout@v3

      - name: üóùÔ∏è Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          create_credentials_file: true
          token_format: access_token
          workload_identity_provider: ${{ secrets.IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

      - name: full project number with version
        uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: number-with-version
          runtime: python38
          entry_point: main
          source_dir: src/erap
          service_account_email: cloud-function-sa@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com
          event_trigger_type: providers/cloud.pubsub/eventTypes/topic.publish
          event_trigger_resource: projects/${{ secrets.PROJECT_ID }}/topics/erap-scheduler
          deploy_timeout: 600
          secret_volumes: |
            /secrets/app/secrets.json=projects/${{secrets.PROJECT_NUMBER}}/secrets/secrets/versions/1
            /secrets/ftp/known_hosts=projects/${{secrets.PROJECT_NUMBER}}/secrets/known_hosts/versions/1

  test-secret-4:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    environment:
      name: dev
    permissions:
      id-token: write
      contents: read

    steps:
      - name: ‚¨áÔ∏è Set up code
        uses: actions/checkout@v3

      - name: üóùÔ∏è Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          create_credentials_file: true
          token_format: access_token
          workload_identity_provider: ${{ secrets.IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

      - name: full project number with implied latest
        uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: number-with-implied-version
          runtime: python38
          entry_point: main
          source_dir: src/erap
          service_account_email: cloud-function-sa@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com
          event_trigger_type: providers/cloud.pubsub/eventTypes/topic.publish
          event_trigger_resource: projects/${{ secrets.PROJECT_ID }}/topics/erap-scheduler
          deploy_timeout: 600
          secret_volumes: |
            /secrets/app/secrets.json=projects/${{secrets.PROJECT_NUMBER}}/secrets/secrets
            /secrets/ftp/known_hosts=projects/${{secrets.PROJECT_NUMBER}}/secrets/known_hosts

  test-secret-5:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    environment:
      name: dev
    permissions:
      id-token: write
      contents: read

    steps:
      - name: ‚¨áÔ∏è Set up code
        uses: actions/checkout@v3

      - name: üóùÔ∏è Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          create_credentials_file: true
          token_format: access_token
          workload_identity_provider: ${{ secrets.IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

      - name: partial project id with implied latest
        uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: partial-project-with-implied-version
          runtime: python38
          entry_point: main
          source_dir: src/erap
          service_account_email: cloud-function-sa@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com
          event_trigger_type: providers/cloud.pubsub/eventTypes/topic.publish
          event_trigger_resource: projects/${{ secrets.PROJECT_ID }}/topics/erap-scheduler
          deploy_timeout: 600
          secret_volumes: |
            /secrets/app/secrets.json=${{secrets.PROJECT_ID}}/secrets/secrets
            /secrets/ftp/known_hosts=${{secrets.PROJECT_ID}}/secrets/known_hosts

  test-secret-6:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    environment:
      name: dev
    permissions:
      id-token: write
      contents: read

    steps:
      - name: ‚¨áÔ∏è Set up code
        uses: actions/checkout@v3

      - name: üóùÔ∏è Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          create_credentials_file: true
          token_format: access_token
          workload_identity_provider: ${{ secrets.IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

      - name: partial project number with implied latest
        uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: partial-number-with-implied-version
          runtime: python38
          entry_point: main
          source_dir: src/erap
          service_account_email: cloud-function-sa@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com
          event_trigger_type: providers/cloud.pubsub/eventTypes/topic.publish
          event_trigger_resource: projects/${{ secrets.PROJECT_ID }}/topics/erap-scheduler
          deploy_timeout: 600
          secret_volumes: |
            /secrets/app/secrets.json=${{secrets.PROJECT_NUMBER}}/secrets/secrets
            /secrets/ftp/known_hosts=${{secrets.PROJECT_NUMBER}}/secrets/known_hosts
